source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.properties,\
               plugin.xml,\
               schema/,\
               COPYRIGHT,\
               about.html,\
               epl-1.0.txt,\
               lib/istack-commons-runtime-3.0.7.jar,\
               lib/javax.activation-api-1.2.0.jar,\
               lib/jaxb-api-2.3.1.jar,\
               lib/jaxb-runtime-2.3.1.jar
src.includes = COPYRIGHT,\
               about.html,\
               epl-1.0.txt
jars.compile.order = .
javacDefaultEncoding.. = UTF-8
               