<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>eval4_action_client_cpp_pkg</name>
  <version>0.0.1</version>
  <description>C++ action client node that sends Fibonacci goals periodically.</description>
  <maintainer email="todo@example.com">rsdlab</maintainer>
  <license>GPL-3.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <!-- Core dependencies -->
  <build_depend>lifecycle_msgs</build_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <build_depend>rclcpp</build_depend>
  <exec_depend>rclcpp</exec_depend>
  <build_depend>rclcpp_lifecycle</build_depend>
  <exec_depend>rclcpp_lifecycle</exec_depend>

  <!-- Action dependencies -->
  <build_depend>action_msgs</build_depend>
  <exec_depend>action_msgs</exec_depend>
  <build_depend>example_interfaces</build_depend>
  <exec_depend>example_interfaces</exec_depend>
  <build_depend>rclcpp_action</build_depend>
  <exec_depend>rclcpp_action</exec_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
