<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>eval5_robot_cpp_pkg</name>
  <version>0.0.1</version>
  <description>C++ robot-side all-in-one sample node with topics, services, actions, timers, parameters, and custom interfaces. 言語: C++</description>
  <maintainer email="todo@example.com">rsdlab</maintainer>
  <license>LGPL-3.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <!-- Core dependencies -->
  <depend>lifecycle_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>

  <!-- Parameter / descriptor dependencies -->
  <depend>rcl_interfaces</depend>

  <!-- Topic message dependencies -->
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <!-- Service dependencies -->
  <depend>eval5_robot_cpp_pkg_interfaces</depend>

  <!-- Action dependencies -->
  <depend>action_msgs</depend>
  <depend>rclcpp_action</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
