source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               lib/,\
               schema/,\
               plugin.properties,\
               COPYRIGHT,\
               about.html,\
               NOTICE.txt,\
               epl-1.0.txt,\
               lib/influent.jar,\
               lib/org.msgpack.jar,\
               lib/slf4j-api-1.7.13.jar,\
               lib/jackson-annotations-2.10.2.jar,\
               lib/jackson-core-2.10.2.jar,\
               lib/jackson-databind-2.10.2.jar,\
               lib/commons-csv-1.8.jar,\
               lib/jakarta.transaction-api-2.0.1.jar,\
               lib/openjdk-orb-10.1.1.Final.jar
src.includes = lib/,\
               COPYRIGHT,\
               NOTICE.txt,\
               about.html,\
               epl-1.0.txt
javacDefaultEncoding.. = UTF-8
